import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type, type Static } from "typebox";
import { createBackgroundToolManager } from "./background-tool.ts";
import { runCodexSearch } from "./process.ts";

const QuerySchema = Type.Object({
  query: Type.String({
    minLength: 1,
    description: "Focused research request or free-form image intent, forwarded without a mandatory visual template. Include only the artifact and iteration directions the user actually wants.",
  }),
  effort: Type.Optional(Type.Union([
    Type.Literal("quick"),
    Type.Literal("research"),
  ], {
    description: "Semantic effort profile. Omit to use quick. The helper owns the profile's default model and reasoning.",
  })),
  image: Type.Optional(Type.Boolean({
    description: "Generate an image with Codex/ImageGen, save it in the Pi workspace, and let Pi inspect and iterate the artifact. Forces the research profile and requires write: true.",
  })),
  write: Type.Optional(Type.Boolean({
    description: "Use Codex workspace-write with the Pi session cwd as the primary workspace for this call. Required for image generation; omit or use false for read-only research.",
  })),
  yolo: Type.Optional(Type.Boolean({
    description: "Explicitly bypass Codex approvals and sandboxing for this call. Extremely dangerous; use only when the user specifically requests it.",
  })),
});

export type CodexSearchInput = Static<typeof QuerySchema>;

export default function codexSearchExtension(pi: ExtensionAPI) {
  const background = createBackgroundToolManager(pi, {
    namespace: "codex-search",
    statusLabel: "codex_search",
    maxActive: 4,
  });

  pi.registerTool(background.wrapTool({
    name: "codex_search",
    label: "Codex Search + Image",
    description: "Run the codex_search helper for blocked-page fallback, independent web research, or image generation. With image: true, Pi can request, save, inspect, and iterate images generated by the Codex/ImageGen backend; the research profile is always used. Pi does not generate pixels directly, but operationally delivers the final image artifact. The fixed quick/research profiles preserve existing research behavior and isolate model and reasoning selection from the host Codex config. Calls are read-only by default; write explicitly selects workspace-write with the Pi session cwd as its primary workspace, and yolo is an explicit unsandboxed opt-in. In print mode, the tool waits and returns the result directly. In other modes, it runs asynchronously: the call returns immediately after starting bounded background work and completion arrives later as one background result. Research results are model-produced and must be verified against primary sources; this reminder does not apply to image results. The prompt is sent through stdin without a shell; captured output is limited to 48,000 bytes.",
    promptSnippet: "Run Codex web research or Codex/ImageGen image generation",
    promptGuidelines: [
      "Use codex_search when ordinary browser fetching is blocked or insufficient, or for an independent second research path; request URLs or citations when relevant and verify primary sources separately.",
      "For image generation, set image: true and write: true and forward the user's free-form intent. Do not rewrite it into a rigid visual template or require post-processing; the agent decides whether to request candidates, inspect, iterate, or perform calling-task-requested mechanical conversions. Codex/ImageGen generates the pixels; Pi can operationally deliver the final image.",
      "Omit write and yolo unless the user explicitly requests the capability. write uses workspace-write with the Pi session cwd as its primary workspace; yolo bypasses both approvals and sandboxing and is extremely dangerous.",
      "Never use yolo for image generation without the user's specific authorization for yolo.",
      "When multiple codex_search calls or other calls are independently useful, start them in the same turn so Pi can run them concurrently; outside print mode, do not wait for one result before starting another.",
      "In print mode, codex_search returns its result directly; inspect it before continuing dependent work.",
      "Outside print mode, after codex_search starts a background operation, never wait, sleep, or poll for its result. Continue only useful independent work or end the response so the later background result can be delivered. When write or yolo is enabled, do not read or modify potentially overlapping workspace paths until that result arrives.",
    ],
    parameters: QuerySchema,
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      const isImage = params.image === true;
      if (isImage && params.write !== true) {
        throw new Error("Image generation requires explicit write: true so Codex can save the artifact in the Pi workspace.");
      }

      let result;
      try {
        result = await runCodexSearch(params.query, ctx.cwd, isImage ? "research" : params.effort ?? "quick", {
          write: params.write,
          yolo: params.yolo,
        }, signal);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error([
          message,
          "IMPORTANT: You MUST report this codex_search failure in your next user-facing response. You MUST NOT stop or abandon the task solely because codex_search failed; continue with another appropriate tool when useful or available.",
        ].join("\n\n"));
      }
      let text = result.stdout.trimEnd();
      if (!text) text = `codex_search completed without returning ${isImage ? "image output" : "research output"}.`;
      if (result.stdoutTruncated) text += `\n\n[${isImage ? "Image" : "Research"} output truncated to 48,000 bytes.]`;
      if (!isImage) {
        text += "\n\n[Reminder: this is model-produced research, not a verified primary source. Verify cited URLs and primary sources before relying on it.]";
      }

      return {
        content: [{ type: "text", text }],
        details: {
          outputTruncated: result.stdoutTruncated,
          diagnosticsTruncated: result.stderrTruncated,
        },
      };
    },
  }));
}
